import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Preloader from "@/components/Preloader";
import Container from "@/components/ui/Container";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Next e-store - Registration",
    description: "Generated by create next app",
};

export default function ResetLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Preloader />
            
        <Container className="relative p-6 bg-white z-1 dark:bg-gray-900 sm:p-0">
            <Container
                className="flex flex-col justify-center w-full h-screen dark:bg-gray-900 sm:p-0 lg:flex-row"
            >
                {children}
            </Container>
        </Container>
        </>

    );
}
